testing:
	g++ -std=c++0x ../src/ballot.cc ../src/opl.cc ../src/candidate.cc ../src/ir.cc ../src/party.cc ../src/election.cc ../src/election_official.cc test.cc  ../src/PO.cc -lgtest -lgtest_main -pthread -o testing

clean:
	$(RM) *.o audit* testing
